// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestLoginDo struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestLoginDo) Reset()         { *m = RequestLoginDo{} }
func (m *RequestLoginDo) String() string { return proto.CompactTextString(m) }
func (*RequestLoginDo) ProtoMessage()    {}
func (*RequestLoginDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *RequestLoginDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestLoginDo.Unmarshal(m, b)
}
func (m *RequestLoginDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestLoginDo.Marshal(b, m, deterministic)
}
func (m *RequestLoginDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestLoginDo.Merge(m, src)
}
func (m *RequestLoginDo) XXX_Size() int {
	return xxx_messageInfo_RequestLoginDo.Size(m)
}
func (m *RequestLoginDo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestLoginDo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestLoginDo proto.InternalMessageInfo

func (m *RequestLoginDo) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *RequestLoginDo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ResponseLoginDo struct {
	Code                 int64      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items                *LoginUser `protobuf:"bytes,3,opt,name=items,proto3" json:"items,omitempty"`
	Count                int64      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ResponseLoginDo) Reset()         { *m = ResponseLoginDo{} }
func (m *ResponseLoginDo) String() string { return proto.CompactTextString(m) }
func (*ResponseLoginDo) ProtoMessage()    {}
func (*ResponseLoginDo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *ResponseLoginDo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseLoginDo.Unmarshal(m, b)
}
func (m *ResponseLoginDo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseLoginDo.Marshal(b, m, deterministic)
}
func (m *ResponseLoginDo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseLoginDo.Merge(m, src)
}
func (m *ResponseLoginDo) XXX_Size() int {
	return xxx_messageInfo_ResponseLoginDo.Size(m)
}
func (m *ResponseLoginDo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseLoginDo.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseLoginDo proto.InternalMessageInfo

func (m *ResponseLoginDo) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseLoginDo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseLoginDo) GetItems() *LoginUser {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ResponseLoginDo) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type LoginUser struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUser) Reset()         { *m = LoginUser{} }
func (m *LoginUser) String() string { return proto.CompactTextString(m) }
func (*LoginUser) ProtoMessage()    {}
func (*LoginUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *LoginUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUser.Unmarshal(m, b)
}
func (m *LoginUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUser.Marshal(b, m, deterministic)
}
func (m *LoginUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUser.Merge(m, src)
}
func (m *LoginUser) XXX_Size() int {
	return xxx_messageInfo_LoginUser.Size(m)
}
func (m *LoginUser) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUser.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUser proto.InternalMessageInfo

func (m *LoginUser) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestLoginDo)(nil), "proto.RequestLoginDo")
	proto.RegisterType((*ResponseLoginDo)(nil), "proto.ResponseLoginDo")
	proto.RegisterType((*LoginUser)(nil), "proto.LoginUser")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x8d, 0x69, 0xaa, 0x9d, 0x82, 0x96, 0x41, 0x4b, 0xe8, 0xa9, 0xe4, 0x20, 0x3d, 0xf5,
	0x50, 0x4f, 0x7a, 0xee, 0x45, 0xf0, 0xb4, 0xe2, 0x07, 0x68, 0x93, 0xa1, 0x2c, 0x98, 0x4c, 0xdc,
	0xc9, 0xea, 0xd7, 0x2f, 0xfb, 0x2f, 0x90, 0x53, 0xde, 0xcb, 0xdb, 0x79, 0xfb, 0x9b, 0x05, 0xb0,
	0x42, 0x66, 0xdf, 0x1b, 0x1e, 0x18, 0x0b, 0xff, 0xa9, 0x8e, 0xf0, 0xa0, 0xe8, 0xd7, 0x92, 0x0c,
	0x9f, 0x7c, 0xd1, 0xdd, 0x91, 0x71, 0x0d, 0xf3, 0x96, 0xcf, 0xfa, 0x87, 0xca, 0x6c, 0x9b, 0xed,
	0x16, 0x2a, 0x3a, 0xdc, 0xc0, 0x7d, 0x7f, 0x12, 0xf9, 0x67, 0xd3, 0x94, 0xb7, 0x3e, 0x19, 0x7d,
	0x65, 0xe1, 0x51, 0x91, 0xf4, 0xdc, 0x09, 0xa5, 0x1a, 0x84, 0x59, 0xcd, 0x4d, 0x28, 0xc9, 0x95,
	0xd7, 0xb8, 0x82, 0xbc, 0x95, 0x4b, 0x9c, 0x76, 0x12, 0x5f, 0xa0, 0xd0, 0x03, 0xb5, 0x52, 0xe6,
	0xdb, 0x6c, 0xb7, 0x3c, 0xac, 0x02, 0xdc, 0xde, 0x97, 0x7c, 0x0b, 0x19, 0x15, 0x62, 0x7c, 0x82,
	0xa2, 0x66, 0xdb, 0x0d, 0xe5, 0xcc, 0xd7, 0x05, 0x53, 0xbd, 0xc1, 0x62, 0x3c, 0xe9, 0xca, 0xad,
	0x6e, 0xe2, 0x7d, 0x4e, 0x3a, 0x62, 0xb7, 0x70, 0x77, 0x6a, 0x29, 0x11, 0x27, 0x7f, 0xf8, 0x80,
	0xa5, 0x9b, 0xfa, 0x22, 0xf3, 0xa7, 0x6b, 0xc2, 0x77, 0xb8, 0x4b, 0xe0, 0xcf, 0x91, 0x61, 0xfa,
	0x2c, 0x9b, 0xf5, 0xf8, 0x7b, 0xb2, 0x67, 0x75, 0x73, 0x9e, 0xfb, 0xe0, 0xf5, 0x1a, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0x62, 0x16, 0xe0, 0x5e, 0x01, 0x00, 0x00,
}
