// Code generated by protoc-gen-go. DO NOT EDIT.
// source: video.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestChannelAdvert struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChannelAdvert) Reset()         { *m = RequestChannelAdvert{} }
func (m *RequestChannelAdvert) String() string { return proto.CompactTextString(m) }
func (*RequestChannelAdvert) ProtoMessage()    {}
func (*RequestChannelAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{0}
}

func (m *RequestChannelAdvert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChannelAdvert.Unmarshal(m, b)
}
func (m *RequestChannelAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChannelAdvert.Marshal(b, m, deterministic)
}
func (m *RequestChannelAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChannelAdvert.Merge(m, src)
}
func (m *RequestChannelAdvert) XXX_Size() int {
	return xxx_messageInfo_RequestChannelAdvert.Size(m)
}
func (m *RequestChannelAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChannelAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChannelAdvert proto.InternalMessageInfo

func (m *RequestChannelAdvert) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type ResponseChannelAdvert struct {
	Code                 int64                `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string               `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items                []*ChannelAdvertData `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Count                int64                `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ResponseChannelAdvert) Reset()         { *m = ResponseChannelAdvert{} }
func (m *ResponseChannelAdvert) String() string { return proto.CompactTextString(m) }
func (*ResponseChannelAdvert) ProtoMessage()    {}
func (*ResponseChannelAdvert) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{1}
}

func (m *ResponseChannelAdvert) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChannelAdvert.Unmarshal(m, b)
}
func (m *ResponseChannelAdvert) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChannelAdvert.Marshal(b, m, deterministic)
}
func (m *ResponseChannelAdvert) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChannelAdvert.Merge(m, src)
}
func (m *ResponseChannelAdvert) XXX_Size() int {
	return xxx_messageInfo_ResponseChannelAdvert.Size(m)
}
func (m *ResponseChannelAdvert) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChannelAdvert.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChannelAdvert proto.InternalMessageInfo

func (m *ResponseChannelAdvert) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseChannelAdvert) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseChannelAdvert) GetItems() []*ChannelAdvertData {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ResponseChannelAdvert) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ChannelAdvertData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle             string   `protobuf:"bytes,3,opt,name=subTitle,proto3" json:"subTitle,omitempty"`
	AddTime              int64    `protobuf:"varint,4,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Img                  string   `protobuf:"bytes,5,opt,name=img,proto3" json:"img,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelAdvertData) Reset()         { *m = ChannelAdvertData{} }
func (m *ChannelAdvertData) String() string { return proto.CompactTextString(m) }
func (*ChannelAdvertData) ProtoMessage()    {}
func (*ChannelAdvertData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{2}
}

func (m *ChannelAdvertData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelAdvertData.Unmarshal(m, b)
}
func (m *ChannelAdvertData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelAdvertData.Marshal(b, m, deterministic)
}
func (m *ChannelAdvertData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelAdvertData.Merge(m, src)
}
func (m *ChannelAdvertData) XXX_Size() int {
	return xxx_messageInfo_ChannelAdvertData.Size(m)
}
func (m *ChannelAdvertData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelAdvertData.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelAdvertData proto.InternalMessageInfo

func (m *ChannelAdvertData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChannelAdvertData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ChannelAdvertData) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *ChannelAdvertData) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *ChannelAdvertData) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *ChannelAdvertData) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type RequestChannelHotList struct {
	ChannelId            string   `protobuf:"bytes,1,opt,name=channelId,proto3" json:"channelId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestChannelHotList) Reset()         { *m = RequestChannelHotList{} }
func (m *RequestChannelHotList) String() string { return proto.CompactTextString(m) }
func (*RequestChannelHotList) ProtoMessage()    {}
func (*RequestChannelHotList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{3}
}

func (m *RequestChannelHotList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestChannelHotList.Unmarshal(m, b)
}
func (m *RequestChannelHotList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestChannelHotList.Marshal(b, m, deterministic)
}
func (m *RequestChannelHotList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestChannelHotList.Merge(m, src)
}
func (m *RequestChannelHotList) XXX_Size() int {
	return xxx_messageInfo_RequestChannelHotList.Size(m)
}
func (m *RequestChannelHotList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestChannelHotList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestChannelHotList proto.InternalMessageInfo

func (m *RequestChannelHotList) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

type ResponseChannelHotList struct {
	Code                 int64                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string                `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Items                []*ChannelHotListData `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	Count                int64                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResponseChannelHotList) Reset()         { *m = ResponseChannelHotList{} }
func (m *ResponseChannelHotList) String() string { return proto.CompactTextString(m) }
func (*ResponseChannelHotList) ProtoMessage()    {}
func (*ResponseChannelHotList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{4}
}

func (m *ResponseChannelHotList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseChannelHotList.Unmarshal(m, b)
}
func (m *ResponseChannelHotList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseChannelHotList.Marshal(b, m, deterministic)
}
func (m *ResponseChannelHotList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseChannelHotList.Merge(m, src)
}
func (m *ResponseChannelHotList) XXX_Size() int {
	return xxx_messageInfo_ResponseChannelHotList.Size(m)
}
func (m *ResponseChannelHotList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseChannelHotList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseChannelHotList proto.InternalMessageInfo

func (m *ResponseChannelHotList) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResponseChannelHotList) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ResponseChannelHotList) GetItems() []*ChannelHotListData {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *ResponseChannelHotList) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ChannelHotListData struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SubTitle             string   `protobuf:"bytes,3,opt,name=subTitle,proto3" json:"subTitle,omitempty"`
	AddTime              int64    `protobuf:"varint,4,opt,name=addTime,proto3" json:"addTime,omitempty"`
	Img                  string   `protobuf:"bytes,5,opt,name=img,proto3" json:"img,omitempty"`
	Img1                 string   `protobuf:"bytes,6,opt,name=img1,proto3" json:"img1,omitempty"`
	EpisodesCount        int64    `protobuf:"varint,7,opt,name=episodesCount,proto3" json:"episodesCount,omitempty"`
	IsEnd                int64    `protobuf:"varint,8,opt,name=isEnd,proto3" json:"isEnd,omitempty"`
	Comment              int64    `protobuf:"varint,9,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChannelHotListData) Reset()         { *m = ChannelHotListData{} }
func (m *ChannelHotListData) String() string { return proto.CompactTextString(m) }
func (*ChannelHotListData) ProtoMessage()    {}
func (*ChannelHotListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ad4ea8866efb1e3, []int{5}
}

func (m *ChannelHotListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChannelHotListData.Unmarshal(m, b)
}
func (m *ChannelHotListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChannelHotListData.Marshal(b, m, deterministic)
}
func (m *ChannelHotListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelHotListData.Merge(m, src)
}
func (m *ChannelHotListData) XXX_Size() int {
	return xxx_messageInfo_ChannelHotListData.Size(m)
}
func (m *ChannelHotListData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelHotListData.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelHotListData proto.InternalMessageInfo

func (m *ChannelHotListData) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ChannelHotListData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ChannelHotListData) GetSubTitle() string {
	if m != nil {
		return m.SubTitle
	}
	return ""
}

func (m *ChannelHotListData) GetAddTime() int64 {
	if m != nil {
		return m.AddTime
	}
	return 0
}

func (m *ChannelHotListData) GetImg() string {
	if m != nil {
		return m.Img
	}
	return ""
}

func (m *ChannelHotListData) GetImg1() string {
	if m != nil {
		return m.Img1
	}
	return ""
}

func (m *ChannelHotListData) GetEpisodesCount() int64 {
	if m != nil {
		return m.EpisodesCount
	}
	return 0
}

func (m *ChannelHotListData) GetIsEnd() int64 {
	if m != nil {
		return m.IsEnd
	}
	return 0
}

func (m *ChannelHotListData) GetComment() int64 {
	if m != nil {
		return m.Comment
	}
	return 0
}

func init() {
	proto.RegisterType((*RequestChannelAdvert)(nil), "proto.RequestChannelAdvert")
	proto.RegisterType((*ResponseChannelAdvert)(nil), "proto.ResponseChannelAdvert")
	proto.RegisterType((*ChannelAdvertData)(nil), "proto.ChannelAdvertData")
	proto.RegisterType((*RequestChannelHotList)(nil), "proto.RequestChannelHotList")
	proto.RegisterType((*ResponseChannelHotList)(nil), "proto.ResponseChannelHotList")
	proto.RegisterType((*ChannelHotListData)(nil), "proto.ChannelHotListData")
}

func init() { proto.RegisterFile("video.proto", fileDescriptor_0ad4ea8866efb1e3) }

var fileDescriptor_0ad4ea8866efb1e3 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x5d, 0xca, 0xd3, 0x40,
	0x14, 0xfd, 0xd2, 0x34, 0xfd, 0xb9, 0xb5, 0x45, 0x87, 0x2a, 0x63, 0xad, 0x50, 0x82, 0x0f, 0x7d,
	0xaa, 0x58, 0x75, 0x01, 0x52, 0x05, 0x85, 0x82, 0x10, 0x8b, 0xef, 0x69, 0xe6, 0x12, 0x07, 0x32,
	0x99, 0x9a, 0x99, 0x74, 0x03, 0xe2, 0x0a, 0x5c, 0x87, 0x3b, 0x73, 0x11, 0x32, 0x3f, 0xad, 0xa6,
	0x0d, 0xd4, 0x27, 0x9f, 0x32, 0xe7, 0x9e, 0x9c, 0x73, 0xe7, 0x1e, 0xe6, 0xc2, 0xe8, 0xc8, 0x19,
	0xca, 0xd5, 0xa1, 0x92, 0x5a, 0x92, 0xc8, 0x7e, 0xe2, 0x57, 0x30, 0x4d, 0xf0, 0x6b, 0x8d, 0x4a,
	0x6f, 0xbe, 0xa4, 0x65, 0x89, 0xc5, 0x1b, 0x76, 0xc4, 0x4a, 0x93, 0x39, 0x0c, 0x33, 0x57, 0xf8,
	0xc0, 0x68, 0xb0, 0x08, 0x96, 0xc3, 0xe4, 0x4f, 0x21, 0xfe, 0x16, 0xc0, 0xc3, 0x04, 0xd5, 0x41,
	0x96, 0x0a, 0x9b, 0x3a, 0x02, 0xdd, 0x4c, 0x32, 0xb4, 0x92, 0x30, 0xb1, 0x67, 0x72, 0x1f, 0x42,
	0xa1, 0x72, 0xda, 0xb1, 0x2e, 0xe6, 0x48, 0x56, 0x10, 0x71, 0x8d, 0x42, 0xd1, 0x70, 0x11, 0x2e,
	0x47, 0x6b, 0xea, 0xee, 0xb4, 0x6a, 0x58, 0xbd, 0x4d, 0x75, 0x9a, 0xb8, 0xdf, 0xc8, 0x14, 0xa2,
	0x4c, 0xd6, 0xa5, 0xa6, 0x5d, 0x6b, 0xeb, 0x40, 0xfc, 0x23, 0x80, 0x07, 0x57, 0x12, 0x32, 0x81,
	0x0e, 0x67, 0xbe, 0x7f, 0x87, 0x33, 0xa3, 0xd5, 0x5c, 0x17, 0xe8, 0xfb, 0x3b, 0x40, 0x66, 0x30,
	0x50, 0xf5, 0x7e, 0x67, 0x89, 0xd0, 0x12, 0x67, 0x4c, 0x28, 0xf4, 0x53, 0xc6, 0x76, 0x5c, 0xa0,
	0xef, 0x77, 0x82, 0x66, 0x12, 0x2e, 0x72, 0x1a, 0xb9, 0x49, 0xb8, 0xc8, 0x4d, 0xa5, 0xae, 0x0a,
	0xda, 0x73, 0x95, 0xba, 0x2a, 0xe2, 0xd7, 0x26, 0x9a, 0xbf, 0x13, 0x7d, 0x2f, 0xf5, 0x96, 0xab,
	0x5b, 0x91, 0x7e, 0x0f, 0xe0, 0xd1, 0x45, 0xa4, 0x27, 0xe1, 0xbf, 0x65, 0xfa, 0xbc, 0x99, 0xe9,
	0xe3, 0x66, 0xa6, 0xde, 0xeb, 0x76, 0xa8, 0xbf, 0x02, 0x20, 0xd7, 0x9a, 0xff, 0x9c, 0x2a, 0x81,
	0x2e, 0x17, 0xf9, 0x0b, 0x1f, 0xab, 0x3d, 0x93, 0x67, 0x30, 0xc6, 0x03, 0x57, 0x92, 0xa1, 0xda,
	0xd8, 0x6b, 0xf7, 0xad, 0x4b, 0xb3, 0x68, 0xee, 0xc5, 0xd5, 0xbb, 0x92, 0xd1, 0x81, 0x1b, 0xca,
	0x02, 0xd3, 0x3b, 0x93, 0x42, 0x60, 0xa9, 0xe9, 0xd0, 0xf5, 0xf6, 0x70, 0xfd, 0x33, 0x80, 0x7b,
	0x9f, 0xcd, 0x5a, 0x7c, 0xc2, 0xea, 0xc8, 0x33, 0x24, 0x5b, 0x18, 0x37, 0x5f, 0xf4, 0x13, 0x1f,
	0x64, 0xdb, 0x9a, 0xcc, 0xe6, 0x67, 0xb2, 0x65, 0x19, 0xe2, 0x3b, 0xf2, 0x11, 0x26, 0x97, 0xaf,
	0xa0, 0xd5, 0xce, 0xb3, 0xb3, 0xa7, 0xed, 0x7e, 0x9e, 0x8e, 0xef, 0xf6, 0x3d, 0xcb, 0xbf, 0xfc,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x84, 0xcf, 0x33, 0x00, 0xcc, 0x03, 0x00, 0x00,
}
